### ISSUE TITLE
placeholderLabel.frame is not Assignment

### ISSUE THREAD

**Issue by lkqin** [yushuyi/SYKeyboardTextField#2]
placeholderLabel.frame  = CGRectMake(0, 0, 300, 36)

**Comment by yushuyi** [comment]
@lkqin
SYKeyboardTextField 在内部对 placeholderLabel  进行frame 的控制。placeholderLabel默认居左显示，  如果想让 placeholderLabel 居中显示 只需要 textAlignment 为 Center 即可。
如果确实有需要自行处理frame。  可以继承  SYKeyboardTextField 重载 layoutSubviews
